
# Una aplicacion python en Google App Engine se configura a través de un 
# archivo con nombre app.yaml, en donde se especifica como las URLs se
# corresponden con controladores (handlers) y archivos estaticos 
# (css,js,etc). Ademas contiene información del ID y la ultima version
# de la aplicación.    

application: x8-mythical-patrol-p
version: 5
runtime: python27
api_version: 1
threadsafe: yes

# Aqui se definen las intrucciones para indicarle al servidor que codigo 
# debe ejecutar cuando se le haga una petición

handlers:
# Esto significa que para cualquier URL que coincida con el patron /.*
# debe utilizar el codigo de aplicacion (intrucciones) en el archivo main.py 
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
