application: afs-cucuta
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /images
  static_dir: public/images

- url: /users/.*
  script: main.application
  login: required

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: latest